### ISSUE TITLE
Create a Leaflet

### ISSUE THREAD

**Issue by assemblyenjoyer1** [assemblyenjoyer1/Security#7]
As a Scrum master of Team Monica I want to have a piece of documentation of what a Leaflet is and how to create one.

Material:
- [Leaflet](https://moodle.itech-bs14.de/course/view.php?id=990)

Acceptance Criteria:
- Create a document about what you learned

**Comment by DanielAuerX** [comment]
Same as #2 ?

**Comment by isjxn** [comment]
Research revealed that a flyer is a better option for this project.
